config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  resources :commitments, only: [:show, :index] do
    resources :user_commitments, only: [:create, :destroy]
  end

  scope "admin", module: "admin", as: "admin" do
    resources :commitments
    resources :users
    resources :themes
  end

  resources :forums, only: [:index, :show] do
    resources :posts do
      resources :replies, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  resources :themes, only: [:show, :index] do
    resources :user_themes, only: [:create, :destroy]
  end
  resources :contact, only: [:new, :create]

  # STATIC ROUTES
  get "/home" => "static#home"
  get "/statistics" => "static#statistics"
  get "/about" => "static#about"
  get "/donate" => "static#donate"
  get "/rgpd" => "static#rgpd"


  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum.rb
class Forum < ApplicationRecord
	belongs_to :commitment, 
		optional: true 

	has_many :posts
	
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
		@commitments = Commitment.all
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
  end
  
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/index.html.erb
<div class='container my-5'>

	<h2 class="text-center mb-4">Tous les Forums</h2>

	<h4 class="mb-2">Le Forum Général</h4>
	<table class="table table-bordered table-striped mb-4">

		<thead>
			<tr class="border-0">
				<th scope="col-md-10 border-0 text-primary">Titre du Forum </th>
				<th scope="col-md-2 m-auto border-0 text-white">Nombre de Posts</th>   
			</tr>
		</thead>

		<tbody>
					<tr>
						<td class="py-2"><%= link_to "Forum Général", forum_path(1) %></td>
						<td class="py-2"><%= Forum.find(1).posts.count%></td>
					</tr>
		</tbody>

	</table>

	<h4 class="mb-3">Les Forums des Mouvements</h4>
	<table class="table table-bordered table-striped border-primary mb-4">

		<thead>
			<tr class="">
				<th scope="col-md-10 text-primary">Titre du Forum</th>
				<th scope="col-md-2 m-auto text-white">Nombre de Posts</th>   
			</tr>
		</thead>

		<tbody>
			<% @commitments.each do |each_commitment| %>
				<% if each_commitment.forum %>
					<tr>
						<td class="py-2 border-bottom-0"><%= link_to each_commitment.title, forum_path(each_commitment.forum) %></td>
						<td class="py-2 border-bottom-0"><%= each_commitment.forum.posts.count%></td>
					</tr>
				<% else %>
					<tr>
						<td class="py-2 "><%= each_commitment.title %></td>
						<td class="py-2 ">n'a pas encore de Forum.</td>
					</tr>
				<% end %>
			<% end %>
		</tbody>

	</table>

</div>

app/views/forums/show.html.erb
<div class="container my-5"> 

	<!-- RULES ALERTS -->
	<!-- IF NOT LOGGED, MUST SIGNIN OR SIGNUP TO USE FORUM ALERT -->
	<% if !(user_signed_in?) %>
		<div class="alert alert-danger aler-dismissible fade show m-0 mb-4">
			Pour répondre participer à ce Forum vous devez vous <%= link_to 'Connecter', new_user_session_path %> ou vous <%= link_to 'Inscrire', new_user_registration_path %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		</div>
	<% end %>
	<% if user_signed_in? %>
		<!-- IF LOGGED, MUST HAVE TAKEN THE COMMITMENT TO USE FORUM ALERT -->
		<% if (@forum.commitment != nil ) && (current_user.commitments.include?(@forum.commitment) == false) %>
			<div class="alert alert-danger alert-dismissible fade show m-0 mb-4">
				Pour participer à ce Forum, vous devez
				<%= link_to "rejoindre le Mouvement #{@forum.commitment.title}", commitment_path(@forum.commitment) %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		<% end %>
	<% end %>

	<div class="container">
		<% if @forum.commitment %>
			<h4 class="mt-4"><%= link_to "Forums", forums_path %> / <%= link_to @forum.commitment.title, forum_path(@forum.id) %></h4>
		<% else %>
			<h4 class="mt-4"><%= link_to "Forums", forums_path %> / <%= link_to "Général", forum_path(@forum.id) %></h4>
		<% end %>

		<% if @forum.posts.count > 0 %>
			<table class="table table-bordered table-striped mt-4">
				<thead>
					<tr>
						<th scope="col">Titre</th>
						<th scope="col">Auteur</th>   
						<th scope="col">Réponses</th>   
						<th scope="col">créé il y a</th>   
						<th scope="col">dernière Réponse</th>   
					</tr>
				</thead>
				<tbody>
					<% @forum.posts.each do |post| %>
						<tr>
							<td class="py-2"><%= link_to post.title, forum_post_path(@forum, post) %></td>
							<td class="py-2"><%= post.user.username %></td>
							<td class="py-2"><%= post.replies.count %></td>
							<td class="py-2"><%= time_ago_in_words(post.created_at) %></td>
							<% if post.replies.count > 0 %>
								<td class="py-2"><%= time_ago_in_words(post.last_reply.created_at) %></td>
							<% else %>
								<td class="py-2">Pas de Réponse</td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% else %>
			<p>Il n'y a pas encore de Post sur ce Forum.</p>
		<% end %>
	</div>

	<div class="container">
		<!-- BACK BUTTON -->
		<%= link_to 'Retour', forums_path, class: "btn btn-secondary btnlink float-right" %>
		<!-- IF FORUM IS NOT LINKED TO A COMMITMENT AND USER LOGGED IN -->
		<!-- OR IF FORUM IS LINKED TO A COMMITMENT AND USER TOOK THIS COMMITMENT -->
		<!-- OR IF USER IS MODERATOR -->
		<% if user_signed_in? %>
			<% if (@forum.commitment == nil) || (@forum.commitment && current_user.commitments.include?(@forum.commitment)) || current_user.role == 'moderator' %>
				<%= link_to 'Créer un Post', new_forum_post_path(@forum), class:'btn btn-primary btnlink float-left' %>
			<% end %>
		<% end %>

	</div>


</div>