config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  resources :commitments, only: [:show, :index] do
    resources :user_commitments, only: [:create, :destroy]
  end

  scope "admin", module: "admin", as: "admin" do
    resources :commitments
    resources :users
    resources :themes
  end

  resources :forums, only: [:index, :show] do
    resources :posts do
      resources :replies, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  resources :themes, only: [:show, :index] do
    resources :user_themes, only: [:create, :destroy]
  end
  resources :contact, only: [:new, :create]

  # STATIC ROUTES
  get "/home" => "static#home"
  get "/statistics" => "static#statistics"
  get "/about" => "static#about"
  get "/donate" => "static#donate"
  get "/rgpd" => "static#rgpd"


  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord

	# VALIDATIONS
	validates :title, presence: true
	validates :description, presence: true
	validates :sources, presence: true

	# LINK TABLES
	# LINK USERS
	has_many :user_themes, dependent: :destroy
	has_many :users, through: :user_themes
	# LINK COMMITMENTS
	has_many :commitment_themes, dependent: :destroy
	has_many :commitments, through: :commitment_themes
	# LINK SOURCES
	has_many :sources, as: :sourceable, dependent: :destroy
	accepts_nested_attributes_for :sources, allow_destroy: true, reject_if: proc { |s_attr| s_attr[:url].blank? }

	# METHODS

	# METHOD FOR LINE_CHART IN THEME#SHOW VIEW
	def users_by_day
		hash = Hash.new
		# SORTING USER_COMMITMENTS BY CREATION DATE TO AN ARRAY
		sorted_array = self.user_themes.all.sort { |a, b| a.created_at <=> b.created_at }
		# CREATING A HASH WHERE EACH DATE FROM FIRST UC CONTAINS VALUE OF UCs CREATED
		sorted_array.each do |each_ut|
			if hash[each_ut.created_at.to_date] == nil
				hash[each_ut.created_at.to_date] = 0
			end
			hash[each_ut.created_at.to_date] += 1
		end
		day_count = sorted_array[0].created_at.to_date
		hash[day_count - 1.days] = 0
		# INCREMENTING WITH PREVIOUS DAY
		while (day_count <= Date.today)
			if hash[day_count] != nil
				hash[day_count] = hash[day_count - 1.days] + hash[day_count]
			else
				hash[day_count] = hash[day_count - 1.days]
			end
			day_count += 1.days
		end
		return hash
	end

end

app/controllers/admin/themes_controller.rb
module Admin
  class ThemesController < ApplicationController
    before_action :find_theme, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :is_user_admin?

    def index
      @themes = Theme.all
    end

		def new
			@theme = Theme.new
			@theme.sources.build
		end

		def create
			@theme = Theme.new(theme_params)
			if @theme.save
				flash[:success] = "Vous avez créé un Thème."
				redirect_to admin_themes_path
			else
				flash[:error] = @theme.errors.full_messages.to_sentence
				redirect_to new_admin_theme_path
			end
		end

		def edit
			# BUILD NEW SOURCE FORM, if count == 1 or == 2
			if @theme.sources.count >= 0 && @theme.sources.count <= 2
				@theme.sources.build
			end
		end

    def update
      if @theme.update(theme_params)
        flash[:success] = "Vous avez bien édité ce Thème."
        redirect_to admin_themes_path
      else
        flash[:error] = @theme.errors.full_messages.to_sentence
        redirect_to edit_admin_theme_path(@theme.id)
      end
    end

    def destroy
      @theme.destroy
      respond_to do |format|
        format.html do
        end
        format.js  do
        end

      end
    end

    private

		def theme_params
			params.require(:theme).permit(:title, :description, sources_attributes: [:id, :title, :media, :url, :description, :category, :_destroy])
		end

    def find_theme
      @theme = Theme.find(params[:id])
    end

    def is_user_admin?
      unless current_user.role == "admin" && user_signed_in?
        flash[:warning] = "Vous n'êtes pas Administrateur."
        redirect_to root_path
      end
    end
    
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

	before_action :store_location

	def index
		@themes = Theme.all
	end

	def show
		@theme = Theme.find(params[:id])
	end

end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/index.html.erb
<div class="container my-5">

	<h2 class="text-center pb-4">Tous les Thèmes</h2>

	<div class="col-md-11 m-auto">

		<% if @themes.count == 0 %>

			<div class="list-group">
				<div class="list-group-item">
					Il n'y a pas de Thème actuellement sur Le Lobby...
				</div>
			</div>

		<% else %>

			<div class="row">

				<% @themes.each do |each_theme| %>
					<div class="col-md-6 p-2">
						<div class="card commitement border-primary text-center" style="min-height: 200px">
							<a href="<%= theme_path(each_theme.id) %>" style="text-decoration: none">
								<div class="card-body">
									<h5 class="card-title text-center">
										<%= fa_icon 'leaf' %> <%= each_theme.title %> <%= fa_icon 'leaf' %>
									</h5>
									<p class="card-text text-center" style="height: 6rem;">
									<%= each_theme.description %>
									</p>
									<p class="card-text text-center mb-0">
									Inscrits : 
									<%= each_theme.users.count %>
									</p>
									<p class="card-text text-center">
									Mouvements :
									<%= each_theme.commitments.count %>
									</p>
									<button class="btn btn-primary text-center mt-3">En savoir plus</button>
								</div>
							</a>
						</div>
					</div>
				<% end %>

			</div>

		<% end %>

	</div>

</div>

app/views/themes/show.html.erb
<div class="container my-5 m-auto">

	<!-- THEME TITLE -->
	<div class="container text-center mt-3 pt-3 pb-3">
		<h1><%= @theme.title%></h1>

		<!-- BUTTON TO FOLLOW A THEME OR UNFOLLOW A THEME -->
		<div class="row justify-content-center">

			<div class="col-md-3 d-flex justify-content-center align-items-center p-0">
				<% if user_signed_in? %>
					<% if current_user.themes.include?(@theme) %>
						<%= link_to "Ne plus suivre ce Thème", theme_user_theme_path(@theme.id, @theme.user_themes.find_by(user: current_user)), method: 'delete', class: 'btn btn-secondary  btnlink mt-3' %>
					<% else %>
						<%= link_to "Suivre ce Thème", theme_user_themes_path(@theme.id), method: 'post', class: "btn btn-primary mt-3 btnlink" %>
					<% end %>
				<% else %>
					<%= link_to "Suivre ce Thème", user_session_path, method: 'get', class: "btn btn-primary mt-3 btn-link" %>
				<% end %>
			</div>

			<!-- BUTTON BACK TO THEME#INDEX.HTML.ERB -->
			<div class="col-md-3 d-flex justify-content-center align-items-center p-0">
				<%= link_to "Retour aux Thèmes", themes_path, class: "btn btn-outline-secondary mt-3 btnlinkoutline text-wrap" %>
			</div>

		</div>

	</div>

	<!-- THEME PRESENTATION GRID -->
	<div class="container mt-3">

		<div class="row">

			<!-- LEFT CELL -->
			<div class="col-md-4">
				<div class="card" style="height: 100%;">
					<h3 class="card-header">Informations</h3>

					<div class="card-body p-0">
						<ul class="list-group list-group-flush">
							<li class="list-group-item bg-secondary pt-1 pb-0"><h5>Description</h5></li>
							<li class="list-group-item">
								<%= @theme.description %>
							</li>
						</ul>
					</div>

				</div>
			</div>

			<div class="col-md-8 firstline">

				<div class="row pb-4">

					<!-- TOP MID CELL -->
					<div class="col-md-7">
						<div class="card" style="height: 100%;">
							<h3 class="card-header">Chiffres</h3>
							<div class="card-body p-0">
								<table class="table table-sm table-striped m-0">
									<thead>
										<tr>
											<th scope="col">Donnée</th>
											<th scope="col">Valeur</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Total utilisateurs</td>
											<td><%= @theme.users.count %></td>
										</tr>
										<% if user_signed_in? %>
											<tr>
												<td>Dans votre Département</td>
												<% if current_user.department == nil %>
													<td>Inconnu</td>
												<% else %>
													<td><%= @theme.users.where(department: current_user.department).count %></td>
												<% end %>
											</tr>
										<% end %>
										<tr>
											<td>Nombre de Mouvements</td>
											<td><%= @theme.commitments.count %></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>

					</div>

					<!-- TOP RIGHT CELL -->
					<div class="cheese col-md-5" style="height: 100%">
						<div class="card">
							<h3 class="card-header">Géographie</h3>
							<div class="card-body p-0">
								<%= pie_chart(@theme.users.group(:department).count, legend: false) %>
								<small class="text-muted m-0 p-0 pl-2">utilisateurs / département</small>
							</div>
						</div>
					</div>

				</div>

				<!-- BOTTOM RIGHT CELL -->
				<div class="row">
					<div class="grafik col-md-12">
						<div class="card m-0">
							<h3 class="card-header">Évolution du nombre d'utilisateurs</h3>
							<div class="card-body">
								<%= line_chart(@theme.users_by_day) %>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- SOURCES -->
  <div class="container mt-4">
    <div class="card">
      <h3 class="card-header text-center">Sources</h3>
      <div class="card-body pb-0 pt-1">
        <div class="row align-items-center">

          <% if @theme.sources.count > 0 %>
            <% @theme.sources.each do |each_source| %>
              <div class="col-md-<%= 12 / @theme.sources.count %>">
                <a href="<%= each_source.url %>" target="_blank">
                  <h5 class="text-center mt-2" style="height: 6rem;"><%= each_source.title %></h5>
                  <h6><small>édité par</small> <%= each_source.media %>.</h6>
                  <p><%= each_source.description %></p>
                </a>
              </div>
            <% end %>
          <% else %>
            </p>Il n'y a pas de Source pour ce Mouvement.</p>
          <% end %>

        </div>
      </div>
    </div>
  </div>


	<!-- THIS THEME'S COMMIMENTS -->
	<div class="container mt-4 border-0">
		<div class="border-0 bg-secondary text-center pt-2 pb-1">
			<h4 class="align-middle">
				Tous les Mouvements pour ce Thème 
			</h4>
		</div>

		<div class="col-md">
    <% if @theme.commitments.count == 0 %>
      <div class="list-group">
        <div class="list-group-item">
          Il n'y a pas de Mouvement pour ce Thème pour le moment.
        </div>
      </div>

    <% else %>

      <div class="row border-0 ">
        <% @theme.commitments.each do |each_commitment| %>

          <div class="col-md-3 p-2">
            <div class="card border-primary commitement " style="min-height: 200px">
              <a href="<%= commitment_path(each_commitment.id)%>" style="text-decoration: none">
                <div class="card-body text-center ">
                  <h6 class="card-title text-center title-card-homepage" style="height: 7rem;">
                    <%= each_commitment.title %>
                  </h6>
                  <p class="card-text text-center">Inscrits : <%= each_commitment.users.count %> </p>
                </div>
              </a>
            </div>
          </div>

        <% end %>
      <% end %>
      </div>
  </div>


	</div>

	<!-- USERS LIST FOR THIS THEME -->
	<div class="container mt-4">

		<div class="border bg-secondary text-center pt-2 pb-1">
			<h4 class="align-middle">
				Liste des utilisateurs suivant ce Thème 
			</h4>
		</div>



		<table class="table table-bordered table-sm">
			<% if @theme.users.count == 0 %>
				<thead>
					<tr><td>Il n'y a pas d'utilisateur ayant rejoint ce Thème pour le moment</td></tr>
				</thead>
			<% else %>
				<thead>
					<tr>
						<th scope="col">Utilisateur</th>
						<th scope="col">Département</th>
						<th scope="col">Nombre de Mouvements rejoints</th>
					</tr>
				</thead>
				<tbody>
					<% @theme.users.each do |each_user| %>
						<tr>
							<td class="py-1"><%= each_user.display %></td>
							<td class="py-1"><%= each_user.department %></td>
							<td class="py-1"><%= each_user.commitments.count %></td>
						</tr>
					<% end %>
				</tbody>
			<% end %>
		</table>

	</div>

</div>