config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  resources :commitments, only: [:show, :index] do
    resources :user_commitments, only: [:create, :destroy]
  end

  scope "admin", module: "admin", as: "admin" do
    resources :commitments
    resources :users
    resources :themes
  end

  resources :forums, only: [:index, :show] do
    resources :posts do
      resources :replies, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  resources :themes, only: [:show, :index] do
    resources :user_themes, only: [:create, :destroy]
  end
  resources :contact, only: [:new, :create]

  # STATIC ROUTES
  get "/home" => "static#home"
  get "/statistics" => "static#statistics"
  get "/about" => "static#about"
  get "/donate" => "static#donate"
  get "/rgpd" => "static#rgpd"


  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	# VALIDATIONS
  validates :username, 
  uniqueness: { message: ": Ce nom d'utilisateur existe déjà" }

  validates :first_name, 
  length: {minimum: 1, maximum: 20},
  allow_blank: true 

  validates :last_name, 
  length: {minimum: 1, maximum: 50},
  allow_blank: true

  has_many :posts
  has_many :replies 
  
  # LINK TABLES
	#	LINK COMMITMENTS
  has_many :user_commitments, dependent: :destroy
  has_many :commitments, through: :user_commitments
	# LINK THEMES
	has_many :user_themes, dependent: :destroy
	has_many :themes, through: :user_themes
	# CALLBACKS
  after_create :assign_default_username
  after_create :welcome_send

	# METHODS

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def assign_default_username
    self.username = "Utilisateur#{self.id}"
    self.save
  end

  def display
    if self.name_display == true
      return "#{self.first_name}  #{self.last_name}"
    else
      return self.username
    end
  end

	def self.count_by_day
    hash = Hash.new

		# SORTING USERS BY CREATION DATE TO AN ARRAY
		sorted_array = self.all.sort { |a, b| a.created_at <=> b.created_at }
		sorted_array.each do |each_user|
			if hash[each_user.created_at.to_date] == nil
				hash[each_user.created_at.to_date] = 0
			end
			hash[each_user.created_at.to_date] += 1
		end
		day_count = sorted_array[0].created_at.to_date
		hash[day_count - 1.days] = 0
		
		# INCREMENTING WITH PREVIOUS DAY
		while (day_count <= Date.today)
			if hash[day_count] != nil
			hash[day_count] = hash[day_count - 1.days] + hash[day_count]
			else
			hash[day_count] = hash[day_count - 1.days]
			end
			day_count += 1.days
		end
		return hash
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :is_user_admin?

    def index
      @users = User.all
    end

    def edit
      @departement = []
      count = 0
      95.times do
        count += 1
        unless count == 20
          @departement << count.to_s
        end
        if count == 2
          @departement += ["2A", "2B"]
        end
      end
    end

    def update
      if @user.update(user_params)
        flash[:success] = "Vous avez modifié l'utilisateur avec succès"
        redirect_to admin_users_path
      else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to edit_admin_user_path(@user.id)
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html do
        end
        format.js do
        end
      end
    end

    private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :username, :first_name, :last_name, :department, :name_display, :accept_mails)
    end

    def is_user_admin?
      unless current_user.role == "admin" && user_signed_in?
        flash[:warning] = "Vous n'êtes pas Administrateur."
        redirect_to root_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  before_action :is_current_user?

  def show
    @user_commitments = UserCommitment.where(user: @user)
  end

  def edit
    @departement = []
    count = 0
    95.times do
      count += 1
      unless count == 20
        @departement << count.to_s
      end
      if count == 2
        @departement += ["2A", "2B"]
      end
    end
  end

  def update
    if @user.update(user_params)
      @user.save
      flash[:success] = "Vous avez modifié vos informations avec succès !"
      redirect_to user_path(current_user)
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to edit_user_path(current_user)
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :first_name, :last_name, :department, :name_display, :accept_mails)
  end

  def is_current_user?
    unless authenticate_user! && current_user == find_user
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<p><label>Nom d'utilisateur</label>
  <%= f.text_field :username, class:"form-control border" %></p>
<p><label>Prénom</label>
  <%= f.text_field :first_name, class:"form-control border" %></p>
<p><label>Nom</label>
  <%= f.text_field :last_name, class:"form-control border" %></p>
<p><label>Email</label>
  <%= f.text_field :email, class:"form-control border" %></p>
<p><label>Département</label><br>
  <%= f.select :department, @departement, {}, class:"form-control col-2 border pl-1" %></p>
<br>
<div class='form-check'>
  <%= f.check_box :name_display, class:"form-check-input" %>
  <label class="form-check-label ml-1">J'accepte que mon prénom et mon nom soient affichés sur le site</label>
</div>
<br>
<div class="form-check">
  <%= f.check_box :accept_mails, class:"form-check-input" %>
  <label class="form-check-label ml-1" >J'accepte de recevoir des emails et newsletters par courrier électronique. <br>
    Je prends connaissance de la Politique de Confidentialité du site Le Lobby.</label>
</div>
<br>
<button type='submit' class='btn btn-success'>Editer le profil</button>

app/views/users/edit.html.erb
<div class="container my-4 d-flex">
  <div class=" align-self-center">
    <h1>Editer mon profil</h1>
    <%= form_for @user do |f|%>
      <%= render 'edit_form', f: f %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container my-5">
	<div class="container m-auto">
		<div class="row mb-5">
			<div class="col-md-12">
				<h5 class="text-dark card-header border-0 text-center"> <%= @user.username %></h5><br/>
				<div class="card-body p-0">
					<table class="table table-sm">
						<tbody>
							<tr class="text-center"><td class="font-weight-bold text-muted">E-mail&#8239:</td><td><%= @user.email %></td></tr>
							<tr class="text-center"><td class="font-weight-bold text-muted">Prénom&#8239:</td><td><%= @user.first_name %></td></tr>
							<tr class="text-center"><td class="font-weight-bold text-muted">Nom&#8239:</td><td><%= @user.last_name %></td></tr>
							<tr class="text-center"><td class="font-weight-bold text-muted">Département&#8239:</td><td><%= @user.department %></td></tr>
							<tr class="text-center"><td class="font-weight-bold text-muted">Mouvements&#8239:</td><td><%= @user.commitments.count %></td></tr>
							<tr class="text-center">
								<td class="font-weight-bold text-muted">Affichage de l'identité&#8239:</td>
								<% if @user.name_display == true %>
									<td>Nom et Prénom</td>
								<% else %>
									<td>Pseudonyme</td>
								<% end %>
							</tr>
							<tr class="text-center"><td class="font-weight-bold text-muted">Inscrit aux emails&#8239:</td>
								<% if @user.accept_mails %>
									<td>Oui</td></tr>
						<% else %>
							<td>Non</td></tr>
					<% end %>
					<tr class="text-center"><td class="font-weight-bold text-muted">Membre depuis&#8239:</td><td><%= @user.created_at.to_date.to_s(:rfc822 ) %></td></tr>
						</tbody>
					</table>
				</div>
			</div>


			</div>
			<div class="row mb-5">
			<div class="col-md-12 d-flex justify-content-sm-between">
				<div class="mb-2 float-right">
					<%= link_to 'Modifier votre profil', edit_user_path(@user), class: 'btn btn-block btn-secondary' %>
				</div>
				<div class="float-right">
					<%= link_to 'Paramètres de connexion', edit_user_registration_path, class: 'btn btn-block btn-outline-secondary' %>
				</div>
			</div>
		</div>


		<!-- COMMITMENTS TAKEN BY USER -->
		<h1 class="border-0 p-3 text-dark mb-0 text-center">
			Les Mouvements que vous avez rejoint
		</h1>
		<div class="card border mt-2 mb-3 ">
			<div class="card-body border-0 p-0 table-responsive">
		<% if @user_commitments.length > 0 %>
			<% @user_commitments.each do |user_commitment| %>
				<table class="table table-sm border-0">
					<thead>
						<tr class="border-0 table-bordered table-primary">
							<th scope="col" class="bg-primary border-0"> <h6>Mouvement</h6></th>
							<th scope="col" class="border-0 bg-primary"> <h6>Description</h6></th>
						</tr>
					</thead>
					<tbody class="border-0">
								<tr>
									<td class="border-0">
										<%= link_to "#{user_commitment.commitment.title}", commitment_path(user_commitment.commitment.id) %>
									</td>
									<td class="border-0">
										<%= user_commitment.commitment.description %>
									</td>
								</tr>
					</tbody>
				</table>
							<% end %>
						<% else %>
					<div class="d-lg-flex justify-content-lg-between align-items-center">
						<p class="m-1">Vous n'avez adhéré à aucun Mouvement pour le moment. </p>
						<%= link_to 'Cliquez ici pour visiter les Mouvements', commitments_path, class: 'btn btn-primary'%>
					</div>
						<% end %>
			</div>
			<% if @user_commitments.length > 0 %>
			<div>
				<%= link_to 'Tous les Mouvements', commitments_path, class: 'btn btn-secondary' %>
			</div>
				<% end %>
		</div>


		<!-- THEMES FOLLOWED BY USER -->
		<h1 class="border-0 p-3 text-dark mb-0 text-center">
			Les Thèmes que vous suivez
		</h1>
		<div class="card border mt-2 mb-3">
			<div class="card-body border-0 p-0 table-responsive">
						<% if @user.themes.length > 0 %>
							<% @user.themes.each do |each_theme| %>
				<table class="table table-sm border-0">
					<thead>
						<tr class="border-0 table-bordered table-primary">
							<th scope="col" class="bg-primary border-0"><h6>Thème</h6></th>
							<th scope="col" class="border-0 bg-primary"><h6>Description</h6></th>
						</tr>
					</thead>
					<tbody class="border-0">
								<tr>
									<td class="border-0">
										<%= link_to "#{each_theme.title}",theme_path(each_theme.id) %>
									</td>
									<td class="border-0">
										<%= each_theme.description %>
									</td>
								</tr>
					</tbody>
				</table>
						<% end %>
				<% if @user.themes.length > 0 %>
			<div>
				<%= link_to "Visiter d'autres Thèmes", themes_path, class: 'btn btn-secondary justify-content-center' %>
			</div>
					<% end %>
						<% else %>
					<div class="d-lg-flex justify-content-between">
						<p class="m-1">Vous ne suivez aucun Thème pour le moment. </p>
					<%= link_to 'Cliquez ici pour visiter les Thèmes', themes_path, class: 'btn btn-primary' %>
					</div>
						<% end %>
		</div>

			</div>
	</div>
</div>