config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  resources :commitments, only: [:show, :index] do
    resources :user_commitments, only: [:create, :destroy]
  end

  scope "admin", module: "admin", as: "admin" do
    resources :commitments
    resources :users
    resources :themes
  end

  resources :forums, only: [:index, :show] do
    resources :posts do
      resources :replies, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  resources :themes, only: [:show, :index] do
    resources :user_themes, only: [:create, :destroy]
  end
  resources :contact, only: [:new, :create]

  # STATIC ROUTES
  get "/home" => "static#home"
  get "/statistics" => "static#statistics"
  get "/about" => "static#about"
  get "/donate" => "static#donate"
  get "/rgpd" => "static#rgpd"


  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, 
		presence: {message: ': Un titre de post est requis'},
		length: {minimum: 5, maximum: 50, message: ': Le titre doit contenir un minimum de 5 et un maximum de 50 caractères'}

	validates :content,
		presence: {message: ': Un contenu de post est requis'},
		length: {minimum: 5, maximum: 500,  message: ': Le titre doit contenir un minimum de 5 et un maximum de 500 caractères'}

	belongs_to :user
	has_many :replies
	belongs_to :forum 

	# METHODS

	def sorted_replies
		sort_array = Array.new
		sort_array = self.replies.sort { |a, b| a.created_at <=> b.created_at }
	end

	def last_reply
		sort_array = Array.new
		sort_array = self.replies.sort { |a, b| b.created_at <=> a.created_at }
		return sort_array[0]
	end

	def current_user_is_author?
		if user_signed_in? && self.user == current_user
			return true
		end
		return false
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_forum, only: [:create, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @reply = Reply.new
    @replies = @post.replies
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.forum = @forum 
    if @post.save
      flash[:success] = "Vous avez créé un nouveau post !"
      redirect_to forum_path(@forum)
    else
      puts @post.errors.messages
      flash[:error] = @post.errors.full_messages.to_sentence
      redirect_to new_forum_post_path
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Vous avez édité votre post avec succès"
      redirect_to forum_post_path(@post.forum, @post)
    else
      flash[:error] = @post.errors.full_messages.to_sentence
      redirect_to edit_forum_post_path(@post.forum, @post)
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Vous avez détruit votre post avec succès"
    redirect_to forum_path(@forum)
  end


  private 

  def set_post
    @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to forums_path
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_forum
    @forum = Forum.find(params[:forum_id])
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<p><label>Titre</label>
  <%= f.text_field :title, class:"form-control border" %></p>
<p><label>Contenu</label>
  <%= f.text_area :content, class:"form-control border" %></p>

app/views/posts/edit.html.erb
<div class="container my-5">
	<h5>Modifier votre Post</h5>
	<%= form_for @post, :url => {:controller => "posts", :action => "update"} do |f|%>
		<%= render 'form', f: f %>
		<button type='submit' class='btn btn-primary btnlink'>Editer le post</button>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="container my-5">

  <%= link_to 'Créer un post', new_post_path%>
  <% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
  <%= post.user.username %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container my-5">
	<h5>Votre Post</h5>
	<%= form_for @post, :url => {:controller => "posts", :action => "create"} do |f| %>
		<%= render 'form', f: f %>
		<button type='submit' class='btn btn-primary'>Créer un post</button>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="container my-5"> 

	<!-- RULES ALERTS -->
	<!-- IF NOT LOGGED, MUST SIGNIN OR SIGNUP TO USE FORUM ALERT -->
	<% if !(user_signed_in?) %>
		<div class="alert alert-danger aler-dismissible fade show m-0 mb-4">
			Pour répondre à ce post vous devez vous <%= link_to 'Connecter', new_user_session_path %> ou vous <%= link_to 'Inscrire', new_user_registration_path %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		</div>
	<% end %>
	<% if user_signed_in? %>
		<!-- IF LOGGED, MUST HAVE TAKEN THE COMMITMENT TO USE FORUM ALERT -->
		<% if (@post.forum.commitment != nil ) && (current_user.commitments.include?(@post.forum.commitment) == false) %>
			<div class="alert alert-danger alert-dismissible fade show m-0 mb-4">
				Pour répondre à ce Post, vous devez 
				<%= link_to "rejoindre le Mouvement #{@post.forum.commitment.title}", commitment_path(@post.forum.commitment) %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		<% end %>
	<% end %>

	<!-- BREADCRUMB -->
	<% if @post.forum.commitment %>
		<h4 class="mt-4"><%= link_to "Forums", forums_path %> / <%= link_to @post.forum.commitment.title, forum_path(@post.forum.id) %> / <%= link_to @post.title, forum_post_path(@post.id) %></h4>
	<% else %>
		<h4 class="mt-4"><%= link_to "Forums", forums_path %> / <%= link_to "Général", forum_path(@post.forum.id) %> / <%= link_to @post.title, forum_post_path(@post.id) %></h4>
	<% end %>

	<!-- POST -->
	<h4 class="text-right">Post</h4>
	<h4><%= @post.title %></h4>
	<div class="row border mb-3 align-items-center"> 

		<!-- POST INFOS -->
		<div class= "col-md-4 p-3 border-right bg-secondary">
			<h5>par <%= @post.user.username %>
			<% if @post.user.role != nil %>
				(<%= @post.user.role %>)
			<% end %>
			</h5>
			<small class="text-muted">créé le <%= @post.created_at.to_formatted_s(:long) %></small><br/>
			<small class="text-muted">édité le <%= @post.updated_at.to_formatted_s(:long) %></small>
			<!-- IF USER LOGGED -->
			<% if user_signed_in? %> 
				<!-- CAN DELETE IF AUTHOR OR MODERATOR -->
				<% if current_user == @post.user || current_user.role == "moderator" %>
					<%= link_to 'Supprimer', forum_post_path(@post.forum, @post), class:'btn btn-outline-secondary  mt-3',method: 'delete', data: {confirm: 'Êtes-vous sûr ?'} %>
				<% end %>
				<!-- CAN EDIT IF AUTHOR -->
				<% if current_user == @post.user %>
					<%= link_to 'Éditer', edit_forum_post_path(@post.forum, @post), class:'btn  btnlinkoutline btn-outline-primary'%>
				<% end %>
			<% end %>
		</div>

		<!-- POST CONTENT -->
		<div class="col-md-8 p-3">
			<%= @post.content %>
		</div>

	</div>

	<!-- REPLIES -->
	<div class="container p-0 mt-3"> 
		<h4 class="mt-4 text-right">Réponses</h4>

		<% if @replies.size >= 1 %>
			<% @post.sorted_replies.each do |reply| %>

				<div class="row border my-1 align-items-center"> 
					<!-- REPLY INFOS -->
					<div class= "col-md-4 p-3 border-right bg-secondary">
						<p>par 
						<%= reply.user.display %>
						<% if reply.user.role != nil %>
							(<%= reply.user.role %>)
						<% end %>
						<br/>
						<small class="text-muted">créé le <%= reply.created_at.to_formatted_s(:long) %></small><br/>
						<small class="text-muted">édité le <%= reply.updated_at.to_formatted_s(:long) %></small>
						</p>
						<% if user_signed_in? && (current_user == reply.user || current_user.role == "moderator") %>
							<%= link_to 'Supprimer', forum_post_reply_path(@post.forum, @post, reply), class:'btn btn-outline-danger m-1', method: 'delete', data: {confirm: "Êtes-vous sûr ?"} %>
						<% end %>
						<% if user_signed_in? && current_user == reply.user %>
							<%= link_to 'Editer', edit_forum_post_reply_path(@post.forum, @post, reply), class:'btn btn-outline-primary m-4' %>
						<% end %>
					</div>
					<!-- REPLY CONTENT -->
					<div class="col-md-8 p-3">
						<%= reply.content %>
					</div>
				</div>

			<% end %>

		<% else %>
			<p>Pas de Réponse à ce Post pour le moment.</p>
		<% end %>

	</div>

	<!-- REPLY BUTTON AND RULES -->
	<div class="row p-0">

		<div class="col-12 p-0">
			<!-- BACK BUTTON -->
			<%= link_to 'Retour', forum_path(@post.forum.id), class: "btn btn-secondary  btnlink float-right" %>
			<!-- IF FORUM IS NOT LINKED TO A COMMITMENT AND USER LOGGED IN -->
			<!-- OR IF FORUM IS LINKED TO A COMMITMENT AND USER TOOK THIS COMMITMENT -->
			<!-- OR IF USER IS MODERATOR -->
			<% if user_signed_in? %>
				<% if (@post.forum.commitment == nil) || (@post.forum.commitment && current_user.commitments.include?(@post.forum.commitment)) || current_user.role == 'moderator' %>
					<%= link_to 'Répondre', new_forum_post_reply_path(@post.forum, @post), class:'btn btn-primary btnlink float-left' %>
				<% end %>
			<% end %>

		</div>
	</div>

</div>